export const DESK_RESERVATİON_FETCH_SUCCESS = 'DESK_RESERVATİON_FETCH_SUCCESS';
export const DESK_RESERVATİON_FETCH_FOR_INFO = 'DESK_RESERVATİON_FETCH_FOR_INFO';
export const DESK_RESERVATİON_BY_USER_FETCH_SUCCESS = 'DESK_RESERVATİON_BY_USER_FETCH_SUCCESS';
export const DESK_RESERVATİON_FETCH_ERROR = 'DESK_RESERVATİON_FETCH_ERROR';
export const DESK_RESERVATİON_ADD = 'DESK_RESERVATİON_ADD';
export const DESK_RESERVATİON_DELETE = 'DESK_RESERVATİON_DELETE';
export const DESK_RESERVATİON_CHECK = 'DESK_RESERVATİON_CHECK';
export const QUIT = 'QUIT';